/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Caso1;

import java.awt.Font;

/**
 *
 * @author alexm
 */
public class FrmDefinitivo extends javax.swing.JFrame {

    /**
     * Creates new form FrmDefinitivo
     */
    public FrmDefinitivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cbxEstudios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSalida = new javax.swing.JTextArea();
        btnCrear = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cbxAfiliacion = new javax.swing.JComboBox<>();
        cbxEspecialidad = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txtNombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        cbxAfiliacion1 = new javax.swing.JComboBox<>();
        cbxEspecialidad1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaSalida1 = new javax.swing.JTextArea();
        btnCrear1 = new javax.swing.JButton();
        btnBorrar1 = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        cbxCategoria = new javax.swing.JComboBox<>();
        txtExperiencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(20, 10, 150, 60);

        txtApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        jPanel1.add(txtApellido);
        txtApellido.setBounds(190, 10, 140, 60);

        cbxEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diplomado", "Taller" }));
        cbxEstudios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estudios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        jPanel1.add(cbxEstudios);
        cbxEstudios.setBounds(10, 90, 150, 80);

        txaSalida.setColumns(20);
        txaSalida.setRows(5);
        jScrollPane1.setViewportView(txaSalida);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 510, 300);

        btnCrear.setText("Crear Asistente");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear);
        btnCrear.setBounds(20, 510, 130, 50);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar);
        btnBorrar.setBounds(170, 510, 90, 50);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(280, 510, 100, 50);

        cbxAfiliacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Essalud", "Ninguna" }));
        cbxAfiliacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Afiliacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        cbxAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAfiliacionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxAfiliacion);
        cbxAfiliacion.setBounds(200, 90, 150, 80);

        cbxEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recursos Humanos", "Gestion de Archivos" }));
        cbxEspecialidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        jPanel1.add(cbxEspecialidad);
        cbxEspecialidad.setBounds(360, 90, 180, 80);

        jTabbedPane1.addTab("Asistente Administrativo", jPanel1);

        jPanel2.setLayout(null);

        txtNombre1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre1);
        txtNombre1.setBounds(14, 25, 150, 60);

        txtApellido1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        jPanel2.add(txtApellido1);
        txtApellido1.setBounds(182, 25, 140, 60);

        cbxAfiliacion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AFP y Essalud", "Ninguna" }));
        cbxAfiliacion1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Afiliacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        cbxAfiliacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAfiliacion1ActionPerformed(evt);
            }
        });
        jPanel2.add(cbxAfiliacion1);
        cbxAfiliacion1.setBounds(14, 120, 150, 80);

        cbxEspecialidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recursos Humanos", "Gestion de Archivos" }));
        cbxEspecialidad1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        jPanel2.add(cbxEspecialidad1);
        cbxEspecialidad1.setBounds(191, 120, 180, 80);

        txaSalida1.setColumns(20);
        txaSalida1.setRows(5);
        jScrollPane2.setViewportView(txaSalida1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(14, 212, 515, 267);

        btnCrear1.setText("Crear Asistente");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrear1);
        btnCrear1.setBounds(14, 491, 130, 50);

        btnBorrar1.setText("Borrar");
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar1);
        btnBorrar1.setBounds(174, 491, 90, 50);

        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir1);
        btnSalir1.setBounds(299, 491, 100, 50);

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        cbxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        jPanel2.add(cbxCategoria);
        cbxCategoria.setBounds(389, 130, 94, 70);

        txtExperiencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Experiencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14))); // NOI18N
        jPanel2.add(txtExperiencia);
        txtExperiencia.setBounds(350, 20, 90, 60);

        jTabbedPane1.addTab("Asistente de Gerencia", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
       
        String nombre=txtNombre.getText();
        String apellido= txtApellido.getText();
        
        String estud=cbxEstudios.getSelectedItem().toString();
        String afili=cbxAfiliacion.getSelectedItem().toString();
        String especi=cbxEspecialidad.getSelectedItem().toString();  
        
        AsistenteAdministrativa nuevo1= new AsistenteAdministrativa(estud,nombre,apellido,especi,afili);
        txaSalida.append(nuevo1.mostrarDatos());
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cbxAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAfiliacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAfiliacionActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
        txtNombre.setText("");
        txtApellido.setText("");
        txaSalida.setText("");
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
       
       txtNombre1.setText("");
       txtApellido1.setText("");
        txtNombre1.requestFocus();
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed
        
        String nombre=txtNombre1.getText();
        String apellido= txtApellido1.getText();
        String  experiencia=txtExperiencia.getText();
        
        String afili=cbxAfiliacion1.getSelectedItem().toString();
        String especi=cbxEspecialidad1.getSelectedItem().toString();
        String cato=cbxCategoria.getSelectedItem().toString();  
        
        AsistenteDeGerencia nuevo2= new AsistenteDeGerencia(cato,afili,nombre,apellido,especi);
        txaSalida1.append(nuevo2.mostrarDatos());
    }//GEN-LAST:event_btnCrear1ActionPerformed

    private void cbxAfiliacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAfiliacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAfiliacion1ActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          txaSalida.setFont(new Font("monospaced",Font.PLAIN,12));
        txaSalida.setFont(new Font("monospaced",Font.PLAIN,12));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDefinitivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDefinitivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDefinitivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDefinitivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDefinitivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cbxAfiliacion;
    private javax.swing.JComboBox<String> cbxAfiliacion1;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxEspecialidad;
    private javax.swing.JComboBox<String> cbxEspecialidad1;
    private javax.swing.JComboBox<String> cbxEstudios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txaSalida;
    private javax.swing.JTextArea txaSalida1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtExperiencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
